### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by JayKay135** [wasabia/flutter_gl#50]
I know that this is probably a lot of work, but is a linux support currently planned or maybe already in work?

**Comment by forthtemple** [comment]
I agree with you. I have attempted to add Linux functionality to flutter_gl myself. I have attempted to merge the code in flutter_gl_windows and https://github.com/alnitak/flutter_opengl which has Linux functionality. My version compiles and runs but instead of the flutter example showing a yellow triangle with a red background it is completely black. I was wondering what I might be doing wrong and was hoping for some feedback. My repository is at:

https://github.com/forthtemple/flutter_gl

and my Linux code is in flutter_gl/linux in this repository.

**Comment by richyo-codes** [comment]
> I agree with you. I have attempted to add Linux functionality to flutter_gl myself. I have attempted to merge the code in flutter_gl_windows and https://github.com/alnitak/flutter_opengl which has Linux functionality. My version compiles and runs but instead of the flutter example showing a yellow triangle with a red background it is completely black. I was wondering what I might be doing wrong and was hoping for some feedback. My repository is at:
> 
> https://github.com/forthtemple/flutter_gl
> 
> and my Linux code is in flutter_gl/linux in this repository.

Is there are reason you reimported the code rather than following standard workflow of forking, and applying your changes on a branch?

**Comment by forthtemple** [comment]
@richyo-work  I've now removed the flutter_gl repository and will fork it at a later date when I have time.

**Comment by anonfaded** [comment]
> @richyo-work I've now removed the flutter_gl repository and will fork it at a later date when I have time.

any updates on ur fork, did you fix the linux support?

**Comment by forthtemple** [comment]
I never forked flutter_gl but instead did a new linux version at:

https://github.com/forthtemple/openworld_gl

It is compatible with my version of three_dart at:

https://github.com/forthtemple/openworlddart

which is designed specifically for open world games. Possibly you could fork flutter_gl and merge my openworld_gl changes into it. Or you could use my openworlddart repository which is fully three_dart compatible and has many three_dart fixes. I did a game at:
https://github.com/forthtemple/stacktower
which uses the openworlddart repository but doesn't use the openworld aspects of it. It just uses the three_dart part. So works fine if you just want to use three_dart. Ive got a linux snap at:
https://snapcraft.io/stacktower

**Comment by anonfaded** [comment]
> never forked flutter_gl but instead did a new linux version at:
> 
> https://github.com/forthtemple/openworld_gl

interesting. But I'm getting error when trying to build for android:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':openworld_gl'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: C:\Users\faded\AppData\Local\Pub\Cache\hosted\pub.dev\openworld_gl-0.0.26\android\build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
```

I will fix this by adding namespace, but i thought this was fixed in your version already. In flutter_gl package i fixed this as well but in the end another initialization issue was arising, right now i m trying your repo and will let you know if i still get that error.


edit: this error is also same as in the original package:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':openworld_gl:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="com.futouapp.flutter_gl.flutter_gl" found in source AndroidManifest.xml: C:\Users\faded\AppData\Local\Pub\Cache\hosted\pub.dev\openworld_gl-0.0.26\android\src\main\AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="com.futouapp.flutter_gl.flutter_gl" from the source AndroidManifest.xml: C:\Users\faded\AppData\Local\Pub\Cache\hosted\pub.dev\openworld_gl-0.0.26\android\src\main\AndroidManifest.xml.
```
I will remove that line and try again building...

edit: third error:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':openworld_gl:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (21).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation
```
The third error got fixed when i added this in the android {...} block :

```bash
    // *** ADD or MODIFY compileOptions ***
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11 // Align with your app
        targetCompatibility JavaVersion.VERSION_11 // Align with your app
    }
    // ********************************

    // *** ADD or MODIFY kotlinOptions ***
    kotlinOptions {
        jvmTarget = '11' // Align with your app (use string '11')
    }
    // *****************************
```

**Comment by anonfaded** [comment]
ok so after all the tweaks in those 3 errors, in the end the main error is still same which was in the original package:

```bash
[Renderer] Flutter GL Native Initialized.
[Renderer] Preparing GL Context...
[Renderer] GL Context Prepared. Texture ID: 1, GL type: OpenGLContextES
[Renderer] _setupGL: Starting...
[Renderer] _setupGL: Compiling Shaders...
[Rend] Shader compiled ok (V)
[Rend] Shader compiled ok (F)
[Renderer] _setupGL: Program Linked (ID: 3).
[Renderer] _setupGL: Creating Vertex Buffer...
[Renderer] !!! ERROR DURING GL SETUP !!!: NoSuchMethodError: The getter 'bufferId' was called on null.
Receiver: null
Tried calling: bufferId
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      OpenGLContextES.bindBuffer (package:openworld_gl/openGL/opengl/OpenGLContextES.dart:349:35)

```

@forthtemple  Can you please guide on what the actual issue is? is it with your code in this package? I used Ai and it says the issue is with the package itself

**Comment by forthtemple** [comment]
Is that issue you're having with the bufferId with android?

**Comment by anonfaded** [comment]
> Is that issue you're having with the bufferId with android?

yes i am making a video editor app, and for the preview widget i m trying to make use of this package but when i open the video project in my app, i get errors regarding gpu initialization. I'm trying to tweak but no success yet

**Comment by forthtemple** [comment]
Are you running on a new android phone? I think I saw that error when using the emulator but might have been for ios.

**Comment by anonfaded** [comment]
> Are you running on a new android phone? I think I saw that error when using the emulator but might have been for ios.

I m using a real android device with android version 11

**Comment by forthtemple** [comment]
Have you tried recreating the android platform?

**Comment by anonfaded** [comment]
> Have you tried recreating the android platform?

Recreate? how, can you elaborate please. Also see what Ai says about this issue:

```bash
Okay, we've hit the same wall again with openworld_gl as we did with flutter_gl:

NoSuchMethodError: The getter 'bufferId' was called on null. inside OpenGLContextES.bindBuffer

Even when we:

    Correctly obtain the Buffer object from _gl.createBuffer().

    Correctly pass this Buffer object to _gl.bindBuffer().

The package's internal implementation of bindBuffer fails because it treats the object as null when trying to access bufferId.

Conclusion:

This definitively demonstrates a bug within the openworld_gl package itself, specifically in its OpenGLContextES.bindBuffer implementation on your testing environment (Android). The wrapper around the native OpenGL call is faulty.

We cannot reliably fix this by changing our application code further. Trying different variations is unlikely to succeed when the underlying library call is broken.
```

Its very confusing after all these issues, no clue what to do now. Also isn't there any updated package that has no issues? or how can we fix this if you know...

**Comment by forthtemple** [comment]
You could try removing the 'android' directory and then recreating with

flutter create --platforms=android .

**Comment by anonfaded** [comment]
> You could try removing the 'android' directory and then recreating with
> 
> flutter create --platforms=android .

i did this now, still exact same error. I think the package itself has issues due to being very old. Isn't there any updated package with no such issues? I'm stuck now and can't move forward due to main thing which i need and it is failing.
